#-----------------------------------------ROUTES STATIQUES------------------------------------------
privacy:
  path: /privacy
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
      template: "statique/privacy.html.twig"

terms:
  path: /terms
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
      template: "statique/terms.html.twig"
